apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spider
  labels:
    app: spider
    tier: backend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: spider
  template:
    metadata:
      labels:
        tier: backend
        app: spider
    spec:
      containers:
      - name: spider
        image: unistd1999/spider:test