apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  labels:
    app: web
    tier: backend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        tier: backend
        app: web
    spec:
      containers:
      - name: web
        image: unistd1999/web
